### ISSUE TITLE
PIR-YX-358A

### ISSUE THREAD

**Issue by EdgarCollett** [peff74/PIR_YX-358A#1]
Hi all, does anyone have information on the attached photo of a, seemingly, newer Detector board? Any assistance would be much appreciated.
![20240804_093003](https://github.com/user-attachments/assets/5aa4d8a9-8e36-4dfb-a150-863cbe08daf7)

**Comment by peff74** [comment]
Send more photos. 
From both PCB front- and backside.

What would you like to change?

**Comment by EdgarCollett** [comment]
![20240804_184802](https://github.com/user-attachments/assets/bb923c1d-12ad-447d-9b77-433c16b0925c)
![20240804_184214](https://github.com/user-attachments/assets/9eaab4a0-1bac-4762-b7ba-bab7b83f496e)
![20240804_184358](https://github.com/user-attachments/assets/508e0a74-4751-4eb9-9930-a824f619d39b)
![20240804_185939](https://github.com/user-attachments/assets/d99ff28e-3f88-4700-8962-d68a46bb1de8)

My circuit has a delay of 45 seconds & I would like to make it longer - About 5 minutes

**Comment by EdgarCollett** [comment]
Sorry, closed by accident.

**Comment by peff74** [comment]
Hi,
I've activated the discussions.
Please create your question there again ;-)

**Comment by EdgarCollett** [comment]
Thank you, will do

Kind regards,

Edgar Collett
081-354-3198
email: ***@***.***

**Comment by peff74** [comment]
I think you have to solder out the PIR to have a look on the chip what is controlling the unit.

**Comment by EdgarCollett** [comment]
Thanks so far - I was afraid that might be the case. I will try tommorow,
but have my doubts if that is possible. Anyway, I have two more units, so
it will be worth it.


Kind regards,

Edgar Collett
081-354-3198
email: ***@***.***

**Comment by peff74** [comment]
look like your device... so maybe you can try R10^^
![image](https://github.com/user-attachments/assets/02e78e0a-f08d-4cf2-b2dc-c895c130959f)

**Comment by EdgarCollett** [comment]
Thank you very much, I will certainly try this & then update the Get Hub
site with the result.

Kind regards,

Edgar Collett
081-354-3198
email: ***@***.***
