### ISSUE TITLE
How to change sensitivity level? 

### ISSUE THREAD

**Issue by guptajpcf** [peff74/PIR_YX-358A#2]
Is there some tweak that could change sensitivity level? Also can this operate in normal day light?

**Comment by peff74** [comment]
To modify the light sensitivity in the SP015A circuit, you can adjust the value R1 (1 MΩ), which together with the LDR form a voltage divider that controls the voltage on the CDS pin (Pin 1 SP015A), depending on ambient light levels.

Increasing the value of R1 will decrease the circuit's sensitivity to light changes, as it will reduce the voltage change at the CDS pin. Conversely, lowering the value of R1 will make the circuit more sensitive to light by allowing a greater voltage variation when the LDR detects light changes.
![image](https://github.com/user-attachments/assets/51c2abe9-053d-47e0-ba1a-a9cb444e3364)
